[package]
name = "sounddisc"
version = "0.1.0"
description = "本地 CD 播放器"
edition = "2021"

[lib]
name = "cdplayer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["rustls"] }
cd-core = { path = "../crates/cd-core" }

[profile.release]
strip = true
